name: CI Frontend
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
     - name: Install dependencies
       run: pip3 install -r frontend/requirements.txt 
     - name: Run Test
       run: python3 frontend/tests/testRunner.py